return {
  authed: false,
  wallet: {
    address: null,
    verified: false,
    verifiedAt: null,
  },
  user: {
    id: 'user_' + Math.random().toString(36).substr(2, 9),
    username: refCode,
    balance: 0,
    totalMined: 0,
    totalPurchased: 0,
    purchaseMultiplier: 1,
    referralMultiplier: 1,
    referrals: 0,
    joinedDate: Date.now(),
    guest: true,
    riskScore: 0,
    referralCode: refCode,
    isAdmin: false,
    priorityAirdrop: false,
    notificationPreferences: {
      session_end: true,
      streak_grace_warning: true,
      boost_expired: true,
      weekly_summary: true,
      airdrop_announcement: true,
    },
  },
  streak: {
    currentStreak: 0,
    lastSessionStartAt: null,
    lastSessionEndAt: null,
    graceEndsAt: null,
    nextMultiplier: 1,
  },
  session: {
    id: '',
    isActive: false,
    startTime: null,
    endTime: null,
    baseRate: 0,
    streakMultiplier: 1,
    boostMultiplier: 1,
    purchaseMultiplier: 1,
    effectiveRate: 0,
    status: "ended",
    sessionMined: 0,
    lastAccruedAt: null,
    baseRatePerHr: 0,
    multiplier: 1,
  },
  activeBoosts: [],
  ledger: [],
  purchaseHistory: [],
  notifications: [],
  walletAddress: null,
  walletVerifiedAt: null,
  currentNonce: null,
};