
import React, { useState } from 'react';
import { AppState, AdProvider } from '../types';
import { PlayCircle, Zap, ShieldCheck, Info, Clock, Loader2, Star, Award } from 'lucide-react';
import { AD_BOOST_MAX_QUEUE_MS } from '../constants';

// Provider-agnostic Ad Integration
class MockAdProvider implements AdProvider {
  private rewardCallback: (() => void) | null = null;

  async loadRewarded(): Promise<void> {
    console.log("Mock Ad Provider: Loading rewarded ad...");
    return new Promise(resolve => setTimeout(resolve, 500));
  }

  async showRewarded(): Promise<boolean> {
    console.log("Mock Ad Provider: Showing rewarded ad...");
    return new Promise(resolve => {
      setTimeout(() => {
        if (this.rewardCallback) this.rewardCallback();
        resolve(true);
      }, 3000);
    });
  }

  onReward(callback: () => void): void {
    this.rewardCallback = callback;
  }
}

interface BoostTabProps {
  state: AppState;
  onApplyAdBoost: () => void;
  currentTime: number;
}

const BoostTab: React.FC<BoostTabProps> = ({ state, onApplyAdBoost, currentTime }) => {
  const [isWatching, setIsWatching] = useState(false);
  const [adProvider] = useState(() => new MockAdProvider());
  
  const adBoost = state.activeBoosts.find(b => b.type === 'AD' && b.expiresAt > currentTime);
  const isAdActive = !!adBoost;

  const handleWatchAd = async () => {
    setIsWatching(true);
    try {
      await adProvider.loadRewarded();
      adProvider.onReward(() => {
        onApplyAdBoost();
      });
      await adProvider.showRewarded();
    } catch (err) {
      console.error("Ad failed to show", err);
    } finally {
      setIsWatching(false);
    }
  };

  const adTimeRemaining = adBoost ? Math.max(0, adBoost.expiresAt - currentTime) : 0;
  const hoursRemaining = Math.floor(adTimeRemaining / (1000 * 60 * 60));
  const minsRemaining = Math.floor((adTimeRemaining % (1000 * 60 * 60)) / (1000 * 60));
  const secsRemaining = Math.floor((adTimeRemaining % (1000 * 60)) / 1000);

  const isQueueFull = adTimeRemaining >= AD_BOOST_MAX_QUEUE_MS;

  // Filter multipliers (currently only AD type is generated by the app)
  const activeMultipliers = state.activeBoosts.filter(b => b.expiresAt > currentTime);
  
  // Status perks are non-multiplicative account-level boosts
  const statusPerks = [
    ...(state.user.priorityAirdrop ? [{
      id: 'priority_airdrop',
      name: 'Priority Airdrop',
      description: 'VIP status for token distribution',
      icon: Star,
      color: 'text-purple-400',
      bgColor: 'bg-purple-500/20'
    }] : []),
    ...(state.user.isAdmin ? [{
      id: 'admin_access',
      name: 'Alpha Access',
      description: 'Early project testing privileges',
      icon: Award,
      color: 'text-teal-400',
      bgColor: 'bg-teal-500/20'
    }] : [])
  ];

  return (
    <div className="px-6 space-y-8 animate-in slide-in-from-bottom-8 duration-500">
      <div>
        <h2 className="text-3xl font-black text-white tracking-tight">Boosters</h2>
        <p className="text-slate-400 text-sm mt-1">Enhance your mining velocity and account value.</p>
      </div>

      {/* Ad Multiplier Section */}
      <div className="glass rounded-[32px] p-8 border border-white/10 relative overflow-hidden text-center">
        <div className="absolute top-0 right-0 p-4 opacity-5">
          <Zap className="w-32 h-32 text-teal-400 fill-teal-400" />
        </div>
        
        <div className="relative z-10 flex flex-col items-center">
          <div className="w-20 h-20 rounded-3xl bg-teal-500/10 flex items-center justify-center text-teal-400 mb-6 border border-teal-500/20 shadow-lg shadow-teal-500/10">
            {isWatching ? <Loader2 className="w-10 h-10 animate-spin" /> : <PlayCircle className="w-10 h-10" />}
          </div>
          <h3 className="text-2xl font-black text-white mb-2">Temporary 2x Multiplier</h3>
          <p className="text-sm text-slate-500 mb-8 max-w-[240px] leading-relaxed">
            Watch a rewarded video to add <span className="text-teal-400 font-bold">1 Hour</span> of double mining speed.
          </p>
          
          {isAdActive && (
            <div className="w-full flex flex-col items-center py-4 mb-4 bg-teal-400/5 rounded-2xl border border-teal-400/20">
              <div className="flex items-center gap-2 text-teal-400 text-3xl font-mono font-black tracking-tight">
                <Clock className="w-6 h-6" />
                {String(hoursRemaining).padStart(2, '0')}:{String(minsRemaining).padStart(2, '0')}:{String(secsRemaining).padStart(2, '0')}
              </div>
              <p className="text-[10px] text-teal-400/70 font-black uppercase tracking-widest mt-1">Remaining Boost Duration</p>
            </div>
          )}

          <button 
            onClick={handleWatchAd}
            disabled={isWatching || isQueueFull}
            className={`w-full h-16 rounded-[24px] font-black uppercase tracking-widest flex items-center justify-center gap-3 transition-all shadow-xl ${
              isWatching || isQueueFull
                ? 'bg-slate-800 text-slate-500 cursor-not-allowed' 
                : 'bg-gradient-to-r from-teal-500 to-emerald-600 text-white shadow-teal-500/20 active:scale-95'
            }`}
          >
            {isWatching ? 'Buffering Ad...' : isQueueFull ? 'Queue Full' : (
              <>
                <Zap className="w-5 h-5 fill-white" />
                Add +1 Hour Boost
              </>
            )}
          </button>
        </div>
      </div>

      {/* Active Perks Summary */}
      <div className="space-y-4">
        <h4 className="text-sm font-black text-slate-400 uppercase tracking-widest ml-1">Active Perks & Status</h4>
        <div className="space-y-3">
          {activeMultipliers.length === 0 && statusPerks.length === 0 && (
            <div className="py-12 text-center glass rounded-[24px] border border-dashed border-white/10">
              <p className="text-sm text-slate-600 font-medium tracking-wide">No active boosters found.</p>
            </div>
          )}
          
          {/* Multiplier Perks */}
          {activeMultipliers.map((boost, idx) => (
            <div key={`boost-${idx}`} className="glass flex items-center justify-between p-5 rounded-[24px] border border-white/5 hover:bg-white/[0.06] transition-all">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-xl bg-purple-500/20 flex items-center justify-center text-purple-400 border border-purple-500/20">
                  <ShieldCheck className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-sm font-black text-white">{boost.type === 'AD' ? 'Ad-Watch Multiplier' : 'Mining Boost'}</p>
                  <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">Efficiency: {boost.multiplier.toFixed(1)}x</p>
                </div>
              </div>
              <div className="text-right">
                <span className="px-3 py-1 bg-green-500/10 text-green-400 text-[10px] font-black rounded-lg border border-green-500/20 uppercase">Active</span>
              </div>
            </div>
          ))}

          {/* Status Perks */}
          {statusPerks.map((perk) => (
            <div key={perk.id} className="glass flex items-center justify-between p-5 rounded-[24px] border border-white/5 hover:bg-white/[0.06] transition-all">
              <div className="flex items-center gap-4">
                <div className={`w-12 h-12 rounded-xl ${perk.bgColor} flex items-center justify-center ${perk.color} border border-white/5`}>
                  <perk.icon className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-sm font-black text-white">{perk.name}</p>
                  <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">{perk.description}</p>
                </div>
              </div>
              <div className="text-right">
                <span className="px-3 py-1 bg-purple-500/10 text-purple-400 text-[10px] font-black rounded-lg border border-purple-500/20 uppercase">Status</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="glass rounded-2xl p-5 flex gap-4 border border-white/5 items-start">
        <Info className="w-5 h-5 text-purple-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="text-xs font-black text-white uppercase tracking-tight">Boost Information</p>
          <p className="text-[11px] text-slate-500 leading-relaxed font-medium">
            Store items now provide direct ECHO balance injections rather than permanent multipliers. Ad-watch boosts stack on top of your current streak multipliers. Priority airdrop status is granted to Resonance package holders.
          </p>
        </div>
      </div>
    </div>
  );
};

export default BoostTab;
